//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Extension_Library.System.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegularExpressionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegularExpressionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System_Extension_Library.System.Text.RegularExpressionResources", typeof(RegularExpressionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICT Chinese Lexical Analysis System Initialization failed..
        /// </summary>
        internal static string NL_CHN_InitializtionFailed_EX {
            get {
                return ResourceManager.GetString("NL_CHN_InitializtionFailed_EX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICT Chinese Lexical Analysis System shutdown failed..
        /// </summary>
        internal static string NL_CHN_ShutdownFailed_EX {
            get {
                return ResourceManager.GetString("NL_CHN_ShutdownFailed_EX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user-word file does not exist..
        /// </summary>
        internal static string NL_CHN_UserWordFileDoesNotExist_EX {
            get {
                return ResourceManager.GetString("NL_CHN_UserWordFileDoesNotExist_EX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.+)? ?(.+) - - \[(.+)\] &quot;(.+) (.+) (.+)/(.+)&quot; ([0-9]+) ([0-9]+) &quot;(.+)&quot; &quot;(.+)&quot;.
        /// </summary>
        internal static string REG_ApacheLogline {
            get {
                return ResourceManager.GetString("REG_ApacheLogline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [\u4e00-\u9fa5]+.
        /// </summary>
        internal static string REG_ChineseCharacter {
            get {
                return ResourceManager.GetString("REG_ChineseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^\x00-\xff]+.
        /// </summary>
        internal static string REG_DoubleByteCharacter {
            get {
                return ResourceManager.GetString("REG_DoubleByteCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b.
        /// </summary>
        internal static string REG_EmailAddress {
            get {
                return ResourceManager.GetString("REG_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (\w[\w\-^@]+\.?)+@serversuffix.
        /// </summary>
        internal static string REG_EmailAddress_0 {
            get {
                return ResourceManager.GetString("REG_EmailAddress_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w+(\.[a-zA-Z^@]{2,3})+.
        /// </summary>
        internal static string REG_EmailAddress_1 {
            get {
                return ResourceManager.GetString("REG_EmailAddress_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b[a-zA-Z0-9&apos;\-]+\b.
        /// </summary>
        internal static string REG_EnglishWordWithNumber {
            get {
                return ResourceManager.GetString("REG_EnglishWordWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;[^&lt;&gt;]+&gt;.
        /// </summary>
        internal static string REG_HTMLMark {
            get {
                return ResourceManager.GetString("REG_HTMLMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&lt;tag&gt;)|(&lt;tag\s+[^&lt;&gt;]*&gt;)|(&lt;/tag&gt;).
        /// </summary>
        internal static string REG_HTMLMark_0 {
            get {
                return ResourceManager.GetString("REG_HTMLMark_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b.
        /// </summary>
        internal static string REG_IPAddress {
            get {
                return ResourceManager.GetString("REG_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b.
        /// </summary>
        internal static string REG_IPAddressWithAccessToEachNumber {
            get {
                return ResourceManager.GetString("REG_IPAddressWithAccessToEachNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b[a-zA-Z&apos;\-]+\b.
        /// </summary>
        internal static string REG_TypicalEnglishWord {
            get {
                return ResourceManager.GetString("REG_TypicalEnglishWord", resourceCulture);
            }
        }
    }
}
