//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoNetExtension.System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoNetExtension.System.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the argument &quot;{0}&quot; is between {1} ({2}) and {3} ({4})..
        /// </summary>
        internal static string ERR_ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ERR_ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of array &quot;{0}&quot; must be equal to {1}..
        /// </summary>
        internal static string ERR_ArrayLengthMustBeEqualToASpecificValue {
            get {
                return ResourceManager.GetString("ERR_ArrayLengthMustBeEqualToASpecificValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array &quot;{0}&quot; is empty..
        /// </summary>
        internal static string ERR_EmptyArray {
            get {
                return ResourceManager.GetString("ERR_EmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection &quot;{0}&quot; is empty..
        /// </summary>
        internal static string ERR_EmptyCollection {
            get {
                return ResourceManager.GetString("ERR_EmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List &quot;{0}&quot; is empty..
        /// </summary>
        internal static string ERR_EmptyList {
            get {
                return ResourceManager.GetString("ERR_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of array &quot;{0}&quot; must be equal to the length of array &quot;{1}&quot;..
        /// </summary>
        internal static string ERR_EqualArrayLengthRequired {
            get {
                return ResourceManager.GetString("ERR_EqualArrayLengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the index is no smaller than {0} and no larger than {1}..
        /// </summary>
        internal static string ERR_IndexOutOfRange {
            get {
                return ResourceManager.GetString("ERR_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position of a bit is not valid..
        /// </summary>
        internal static string ERR_InvalidBitPosition {
            get {
                return ResourceManager.GetString("ERR_InvalidBitPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the specified length is a valid value..
        /// </summary>
        internal static string ERR_InvalidLength {
            get {
                return ResourceManager.GetString("ERR_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of parameter {0} must be no larger than the value of parameter {1}..
        /// </summary>
        internal static string ERR_InvalidMinMax {
            get {
                return ResourceManager.GetString("ERR_InvalidMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value range for parameter {0} is from {1} to {2}..
        /// </summary>
        internal static string ERR_InvalidOutOfRange {
            get {
                return ResourceManager.GetString("ERR_InvalidOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for parameter {0} is invalid..
        /// </summary>
        internal static string ERR_InvalidValue {
            get {
                return ResourceManager.GetString("ERR_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with the same key already exists..
        /// </summary>
        internal static string ERR_KeyAlreadyExist {
            get {
                return ResourceManager.GetString("ERR_KeyAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch to &quot;{0}&quot; at position {1} detected..
        /// </summary>
        internal static string ERR_MisMatch {
            get {
                return ResourceManager.GetString("ERR_MisMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be non-negative..
        /// </summary>
        internal static string ERR_NonNegativeArgumentRequired {
            get {
                return ResourceManager.GetString("ERR_NonNegativeArgumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; must be non-negative..
        /// </summary>
        internal static string ERR_NonNegativeValueRequired {
            get {
                return ResourceManager.GetString("ERR_NonNegativeValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array &quot;{0}&quot; is null..
        /// </summary>
        internal static string ERR_NullArray {
            get {
                return ResourceManager.GetString("ERR_NullArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection &quot;{0}&quot; is null..
        /// </summary>
        internal static string ERR_NullCollection {
            get {
                return ResourceManager.GetString("ERR_NullCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List &quot;{0}&quot; is null..
        /// </summary>
        internal static string ERR_NullList {
            get {
                return ResourceManager.GetString("ERR_NullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be positive..
        /// </summary>
        internal static string ERR_PositiveArgumentRequired {
            get {
                return ResourceManager.GetString("ERR_PositiveArgumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; must be positive..
        /// </summary>
        internal static string ERR_PositiveValueRequired {
            get {
                return ResourceManager.GetString("ERR_PositiveValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A programming error occurs..
        /// </summary>
        internal static string ERR_ProgrammingError {
            get {
                return ResourceManager.GetString("ERR_ProgrammingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Unicode character used for escape is invalid..
        /// </summary>
        internal static string ERR_StringEx_InvalidEscape {
            get {
                return ResourceManager.GetString("ERR_StringEx_InvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure no value to search is also the escape character or a quote character..
        /// </summary>
        internal static string ERR_StringEx_InvalidSearchTarget {
            get {
                return ResourceManager.GetString("ERR_StringEx_InvalidSearchTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start index of a substring must be non-negative and less than the length of the original string..
        /// </summary>
        internal static string ERR_Substring_InvalidStartIndex {
            get {
                return ResourceManager.GetString("ERR_Substring_InvalidStartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  must be smaller or equal to the {1}.
        /// </summary>
        internal static string ERR_ValueIllegallyLargerThanAnother {
            get {
                return ResourceManager.GetString("ERR_ValueIllegallyLargerThanAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be inclusively between {1} and {2}.
        /// </summary>
        internal static string ERR_ValueMustInclusivelyBetween {
            get {
                return ResourceManager.GetString("ERR_ValueMustInclusivelyBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; must be larger than {1} and smaller than {2}..
        /// </summary>
        internal static string ERR_ValueOutOfRange_L_S {
            get {
                return ResourceManager.GetString("ERR_ValueOutOfRange_L_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; must be larger than {1} and smaller than or equal to {2}..
        /// </summary>
        internal static string ERR_ValueOutOfRange_L_SE {
            get {
                return ResourceManager.GetString("ERR_ValueOutOfRange_L_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; must be larger than or equal to {1} and smaller than {2}..
        /// </summary>
        internal static string ERR_ValueOutOfRange_LE_S {
            get {
                return ResourceManager.GetString("ERR_ValueOutOfRange_LE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; must be larger than or equal to {1} and smaller than or equal to {2}..
        /// </summary>
        internal static string ERR_ValueOutOfRange_LE_SE {
            get {
                return ResourceManager.GetString("ERR_ValueOutOfRange_LE_SE", resourceCulture);
            }
        }
    }
}
